force-app/main/default/objects/Message_Template__c/Message_Template__c.object-meta.xml
<CustomObject>
    <description>Approved message templates used by the engagement orchestration layer.</description>
    <label>Message Template</label>
    <nameField>
        <label>Message Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message_Template__c/fields/Active__c.field-meta.xml
<CustomField>
<fullName>Active__c</fullName>
<label>Active</label>
<type>Checkbox</type>
<defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Message_Template__c/fields/Approved_On__c.field-meta.xml
<CustomField>
    <fullName>Approved_On__c</fullName>
    <label>Approvals</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Message_Template__c/fields/Legal_Approved__c.field-meta.xml
<CustomField>
<fullName>Legal_Approved__c</fullName>
<label>Legal Approved</label>
<type>Checkbox</type>
<defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Message_Template__c/fields/Medical_Approved__c.field-meta.xml
<CustomField>
    <fullName>Medical_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message_Template__c/fields/Template_Body__c.field-meta.xml
<CustomField>
<fullName>Template_Body__c</fullName>
<label>Template Body</label>
<type>LongTextArea</type>
<length>32768</length>
</CustomField>

force-app/main/default/classes/ZcoMessageTemplateTriggerHandler.cls
public with sharing class ZcoMessageTemplateTriggerHandler {
    public static void beforeUpdate(
        List<Message_Template__c> newTemplates,
        Map<Id, Message_Template__c> oldTemplates
    ) {
        for (Message_Template__c template : newTemplates) {
            Message_Template__c oldTemplate = oldTemplates.get(template.Id);
            if (template.Template_Body__c != oldTemplate.Template_Body__c) {
                template.Active__c = false;
                template.Medical_Approved__c = false;
                template.Legal_Approved__c = false;
                template.Approved_On__c = null;
            }
        }
    }
}